import type { TacticalCard } from "./types";

export const TACTICAL_CARDS: TacticalCard[] = [
  {
    id: "pase-filtrado",
    name: "Pase filtrado",
    type: "attack",
    description: "Busca romper la línea defensiva con un pase profundo.",
    basePower: 72,
    risk: 45,
    energyCost: 12,
    strongAgainst: ["bloque-bajo", "defensa-lenta"],
    weakAgainst: ["linea-adelantada", "anticipacion"],
    preferredSituations: ["ataque-centro", "contraataque", "ultima-jugada"],
  },
  {
    id: "regate-individual",
    name: "Regate individual",
    type: "attack",
    description: "El jugador intenta superar a su marcador en el uno contra uno.",
    basePower: 70,
    risk: 55,
    energyCost: 14,
    strongAgainst: ["bloque-bajo", "marca-pasiva"],
    weakAgainst: ["barrida-fuerte", "marcar-al-hombre"],
    preferredSituations: ["ataque-banda", "contraataque"],
  },
  {
    id: "centro-al-area",
    name: "Centro al área",
    type: "attack",
    description: "Manda la pelota al área buscando un remate peligroso.",
    basePower: 66,
    risk: 35,
    energyCost: 10,
    strongAgainst: ["bloque-bajo", "defensa-baja"],
    weakAgainst: ["marcar-al-hombre", "bloqueo-aereo"],
    preferredSituations: ["ataque-banda", "corner", "tiro-libre"],
  },
  {
    id: "tiro-lejano",
    name: "Tiro lejano",
    type: "attack",
    description: "Prueba desde fuera del área para sorprender al portero.",
    basePower: 62,
    risk: 60,
    energyCost: 9,
    strongAgainst: ["bloque-bajo", "defensa-encerrada"],
    weakAgainst: ["tapar-disparo", "portero-atento"],
    preferredSituations: ["ataque-centro", "posesion-media", "tiro-libre"],
  },
  {
    id: "pared-rapida",
    name: "Pared rápida",
    type: "attack",
    description: "Una combinación corta para romper la marca rival.",
    basePower: 68,
    risk: 40,
    energyCost: 11,
    strongAgainst: ["defensa-lenta", "presion-desordenada"],
    weakAgainst: ["anticipacion", "marcar-al-hombre"],
    preferredSituations: ["ataque-centro", "posesion-media"],
  },
  {
    id: "tiro-colocado",
    name: "Tiro colocado",
    type: "attack",
    description: "Busca precisión en vez de potencia para vencer al portero.",
    basePower: 65,
    risk: 38,
    energyCost: 10,
    strongAgainst: ["portero-fisico", "defensa-desordenada"],
    weakAgainst: ["portero-atento", "tapar-disparo"],
    preferredSituations: ["ataque-centro", "tiro-libre", "ultima-jugada"],
  },
  {
    id: "presion-alta",
    name: "Presión alta",
    type: "defense",
    description: "El equipo adelanta líneas para recuperar rápido.",
    basePower: 70,
    risk: 50,
    energyCost: 15,
    strongAgainst: ["toque-corto", "pausa-y-control"],
    weakAgainst: ["pelotazo", "pase-filtrado"],
    preferredSituations: ["presion-rival", "posesion-media"],
  },
  {
    id: "bloque-bajo",
    name: "Bloque bajo",
    type: "defense",
    description: "El equipo se junta atrás para cerrar espacios.",
    basePower: 68,
    risk: 25,
    energyCost: 8,
    strongAgainst: ["regate-individual", "tiro-colocado"],
    weakAgainst: ["tiro-lejano", "centro-al-area"],
    preferredSituations: ["ataque-centro", "ataque-banda", "ultima-jugada"],
  },
  {
    id: "barrida-fuerte",
    name: "Barrida fuerte",
    type: "defense",
    description: "Una entrada agresiva para cortar la jugada.",
    basePower: 74,
    risk: 65,
    energyCost: 12,
    strongAgainst: ["regate-individual", "contraataque"],
    weakAgainst: ["pared-rapida", "provocar-falta"],
    preferredSituations: ["contraataque", "ataque-banda"],
  },
  {
    id: "linea-adelantada",
    name: "Línea adelantada",
    type: "defense",
    description: "La defensa intenta dejar al rival en fuera de juego.",
    basePower: 66,
    risk: 52,
    energyCost: 10,
    strongAgainst: ["pase-filtrado", "ataque-directo"],
    weakAgainst: ["regate-individual", "tiro-lejano"],
    preferredSituations: ["contraataque", "ataque-centro"],
  },
  {
    id: "marcar-al-hombre",
    name: "Marcar al hombre",
    type: "defense",
    description: "Un jugador sigue de cerca al rival más peligroso.",
    basePower: 64,
    risk: 30,
    energyCost: 9,
    strongAgainst: ["pared-rapida", "tiro-colocado", "inspiracion-del-crack"],
    weakAgainst: ["cambio-de-banda", "toque-corto"],
    preferredSituations: ["ataque-centro", "ultima-jugada"],
  },
  {
    id: "anticipacion",
    name: "Anticipación",
    type: "defense",
    description: "Lee la jugada antes de que el rival pueda ejecutarla.",
    basePower: 67,
    risk: 42,
    energyCost: 10,
    strongAgainst: ["pase-filtrado", "pared-rapida", "toque-corto"],
    weakAgainst: ["regate-individual", "tiro-lejano"],
    preferredSituations: ["posesion-media", "ataque-centro"],
  },
  {
    id: "toque-corto",
    name: "Toque corto",
    type: "midfield",
    description: "El equipo mueve la pelota con pases cortos para controlar la jugada.",
    basePower: 63,
    risk: 28,
    energyCost: 7,
    strongAgainst: ["bloque-bajo", "defensa-desordenada"],
    weakAgainst: ["presion-alta", "anticipacion"],
    preferredSituations: ["posesion-media", "ataque-centro"],
  },
  {
    id: "cambio-de-banda",
    name: "Cambio de banda",
    type: "midfield",
    description: "Mueve el juego hacia el lado débil de la defensa rival.",
    basePower: 61,
    risk: 35,
    energyCost: 8,
    strongAgainst: ["marcar-al-hombre", "bloque-bajo"],
    weakAgainst: ["anticipacion", "presion-alta"],
    preferredSituations: ["ataque-banda", "posesion-media"],
  },
  {
    id: "pelotazo",
    name: "Pelotazo",
    type: "midfield",
    description: "Busca una pelota directa para saltarse la presión rival.",
    basePower: 58,
    risk: 48,
    energyCost: 6,
    strongAgainst: ["presion-alta", "linea-adelantada"],
    weakAgainst: ["bloque-bajo", "defensa-fisica"],
    preferredSituations: ["presion-rival", "contraataque"],
  },
  {
    id: "pausa-y-control",
    name: "Pausa y control",
    type: "midfield",
    description: "Baja el ritmo para ordenar al equipo y cuidar la pelota.",
    basePower: 60,
    risk: 25,
    energyCost: 6,
    strongAgainst: ["rival-cansado", "partido-caotico"],
    weakAgainst: ["presion-alta", "anticipacion"],
    preferredSituations: ["posesion-media", "presion-rival"],
  },
  {
    id: "ultima-jugada",
    name: "Última jugada",
    type: "special",
    description: "El equipo tira todo lo que le queda en una acción decisiva.",
    basePower: 72,
    risk: 45,
    energyCost: 12,
    strongAgainst: ["rival-nervioso", "momentum-alto"],
    weakAgainst: ["bloque-bajo", "marcar-al-hombre"],
    preferredSituations: ["ultima-jugada"],
  },
  {
    id: "la-hinchada-empuja",
    name: "La hinchada empuja",
    type: "special",
    description: "El ambiente levanta al equipo en un momento complicado.",
    basePower: 55,
    risk: 20,
    energyCost: 5,
    strongAgainst: ["momentum-bajo", "partido-cerrado"],
    weakAgainst: ["derrota-amplia"],
    preferredSituations: ["posesion-media", "ultima-jugada", "presion-rival"],
  },
  {
    id: "todo-o-nada",
    name: "Todo o nada",
    type: "special",
    description: "Una apuesta total por atacar, aunque el equipo quede expuesto.",
    basePower: 82,
    risk: 75,
    energyCost: 18,
    strongAgainst: ["rival-cansado", "necesidad-de-gol"],
    weakAgainst: ["bloque-bajo", "anticipacion"],
    preferredSituations: ["ultima-jugada", "contraataque"],
  },
  {
    id: "enfriar-el-partido",
    name: "Enfriar el partido",
    type: "special",
    description: "Reduce el ritmo del juego para proteger una ventaja.",
    basePower: 58,
    risk: 30,
    energyCost: 7,
    strongAgainst: ["rival-acelerado", "momentum-rival"],
    weakAgainst: ["necesidad-de-gol"],
    preferredSituations: ["posesion-media", "presion-rival", "ultima-jugada"],
  },
];

export function getCardById(cardId: string): TacticalCard | undefined {
  return TACTICAL_CARDS.find((card) => card.id === cardId);
}

export function getCardsByType(type: TacticalCard["type"]): TacticalCard[] {
  return TACTICAL_CARDS.filter((card) => card.type === type);
}